services:
  - type: web
    name: react-javascript-api-backend
    runtime: node
    rootDir: api_users
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        value: https://patriciagea.github.io,http://localhost:5173
      - key: CORS_ORIGINS
        value: http://localhost:5173,https://patriciagea.github.io
